### ISSUE TITLE
Implement Sieve of Eratosthenes to check whether the number is prime or not

### ISSUE THREAD

**Issue by Kanhakhatri065** [ephremdeme/data-structure-and-algorithms#123]

**Comment by Kanhakhatri065** [comment]
Asssign this to me. Thank you.

**Comment by Kanhakhatri065** [comment]
Hey, @ephremdeme I have created the PR #127 which solve this issue. Please review the PR

**Comment by ek08** [comment]
Hey @ephremdeme  I have implemented Sieve of Eratosthenes in Java and made a PR #157 in Java
