### ISSUE TITLE
Implement Fibonacci series of a number 

### ISSUE THREAD

**Issue by ephremdeme** [ephremdeme/data-structure-and-algorithms#128]
Accept input integer and print out a series of Fibonacci numbers less than the input number in any language

Example: 
         input: 8
         output: 1, 1, 2, 3, 5, 8

**Comment by codetravellearn** [comment]
i would like to contribute

**Comment by Codedude1** [comment]
Wanna work

**Comment by swastikchugh** [comment]
Hey @ephremdeme 
i have a PR raised for this [https://github.com/ephremdeme/data-structure-and-algorithms/pull/117](url)
Please have a look.

**Comment by Moras-del** [comment]
HI, can you assign me? :)

**Comment by ephremdeme** [comment]
> Hey @ephremdeme
> i have a PR raised for this in JS [https://github.com/ephremdeme/data-structure-and-algorithms/pull/117](url)
> Please have a look.

I don't think the link is working.

**Comment by ephremdeme** [comment]
Go ahead and implement it then send PR

**Comment by swastikchugh** [comment]
Hey @ephremdeme 
Sorry for the incorrect link above
Here it is [](https://github.com/ephremdeme/data-structure-and-algorithms/pull/117)

**Comment by swastikchugh** [comment]
Hey @ephremdeme 
Sorry for the incorrect link
Heres it is [https://github.com/ephremdeme/data-structure-and-algorithms/pull/132](https://github.com/ephremdeme/data-structure-and-algorithms/pull/132)

**Comment by Prash2002** [comment]
hey @ephremdeme 
I have implemented Fibonacci series in Java, please do check it.
here's the link: https://github.com/ephremdeme/data-structure-and-algorithms/pull/137

**Comment by saurabhatram** [comment]
Fibonacci Series in Java [#141](https://github.com/ephremdeme/data-structure-and-algorithms/pull/141)

**Comment by Aniketh896** [comment]
Hey @ephremdeme 
I created Fibonacci Series in Python, please do check it.

I made a Pull Request here - [#165 ](https://github.com/ephremdeme/data-structure-and-algorithms/pull/165#issue-496524091)

**Comment by ishaangupta-YB** [comment]
[https://github.com/ephremdeme/data-structure-and-algorithms/pull/175](url)
Please review my PR.

**Comment by ishaangupta-YB** [comment]
> Accept input integer and print out a series of Fibonacci numbers less than the input number in any language
> 
> Example:
> input: 8
> output: 1, 1, 2, 3, 5, 8

[https://github.com/ephremdeme/data-structure-and-algorithms/pull/178](url)
I have done it in java. Please merge it

**Comment by krishnmohan19** [comment]
hey @ephremdeme 
https://github.com/ephremdeme/data-structure-and-algorithms/pull/183
this is my pull request for fibonacci series in java, please review it.

**Comment by ankitaugale23** [comment]
This is my pull request for the Fibonacci series for c langauge. https://github.com/ephremdeme/data-structure-and-algorithms/pull/184 kindly check it.

**Comment by ephremdeme** [comment]
please move fibonacci folders to Mathematics folder

**Comment by ankitaugale23** [comment]
> please move fibonacci folders to Mathematics folder
I have done it check my pull request #184

**Comment by Kanhakhatri065** [comment]
Has someone tried to implement fibonacci using dynamic programming?

**Comment by khannakshat7** [comment]
@Kanhakhatri065 I can do it in python using dynamic programming.

**Comment by Kanhakhatri065** [comment]
@khannakshat7 sure, I'm gonna assign this to you.

**Comment by khannakshat7** [comment]
@Kanhakhatri065 Please can you review and merge #275

**Comment by Kanhakhatri065** [comment]
Sure.

**Comment by Kanhakhatri065** [comment]
I guess we have more than enough implementations of fibonacci number, so I'm gonna close this issue.
