### ISSUE TITLE
Implement Merge Sort

### ISSUE THREAD

**Issue by ephremdeme** [ephremdeme/data-structure-and-algorithms#2]
Implement merge sort with any language

Input : unsorted array

Output: sorted array

**Comment by ritik-gupta** [comment]
i'm up for this. Can you assign it to me?

**Comment by ephremdeme** [comment]
@all-contributors please add ritik-gupta for code

**Comment by iamvpa** [comment]
Sir, i want to implement this in C++ . Can you assign it to me?

**Comment by Kanhakhatri065** [comment]
I can do this in python. Assign this to me.

**Comment by yashkansal** [comment]
I would like to implement in javascript

**Comment by reethu-annjo** [comment]
May I contribute in Java?

**Comment by amarks444** [comment]
**I can contribute in C++?**

**Comment by Kanhakhatri065** [comment]
Implement it in a language in which it hasn't been implemented yet.
