### ISSUE TITLE
Bogosort Algorithm

### ISSUE THREAD

**Issue by colossal-pepe** [ephremdeme/data-structure-and-algorithms#205]
Also known as the worst sorting algorithm

**Comment by colossal-pepe** [comment]
I would like to do implement this in C++ (for hacktoberfes!).

**Comment by Kanhakhatri065** [comment]
Sure.

**Comment by aderio25** [comment]
Can i also try to implement it with Python?

**Comment by Kanhakhatri065** [comment]
@aderio25 ok, here you go.

**Comment by satrio-pamungkas** [comment]
> @aderio25 ok, here you go.

#289 Ok, here it is Bogo Sort with Python.

**Comment by colossal-pepe** [comment]
#318 here is Bogo sort with C++
