### ISSUE TITLE
N-Queen Problem[Backtracking Algorithm]

### ISSUE THREAD

**Issue by sarveshvhawal007** [ephremdeme/data-structure-and-algorithms#250]
Backtracking Algorithm
**Famous N-Queen Problem**
Language- C++

When Given a number n as input
It outputs the number of ways of arranging queens in that NxN chessboard such that no two queens can kill each other.

for eg: n=4
there are two possible ways which are outputted like this-
.Q..
...Q
Q...
..Q.
----------------------------------------
..Q.
Q...
...Q
.Q..
----------------------------------
for n=3 there are no possibilities and so on....
Can I work on this problem?

**Comment by sarveshvhawal007** [comment]
Can I work on this algo??

**Comment by Kanhakhatri065** [comment]
@sarveshvhawal007 sure, go ahead.
