### ISSUE TITLE
Quick Sort Implementation

### ISSUE THREAD

**Issue by ephremdeme** [ephremdeme/data-structure-and-algorithms#3]
Quick sort implementation with any language

>Input : unsorted array

>Output: sorted array

**Comment by sparshs413** [comment]
I am working on this.

**Comment by ankitksh81** [comment]
@ephremdeme Can I work on this issue for my Hacktoberfest PR?
Do let me know.

**Comment by Ankitkumarjaiswal** [comment]
Hi, @ephremdeme  I would like to contribute towards this issue. I would prefer python or java.

**Comment by Palak-137** [comment]
I will like to implement the quick sort algorithm in a various languages like java, python, c++. Please assign this issue as a part of Hackthoberfest 2020.

**Comment by yashkansal** [comment]
I would like to implement this in java .Plz, assign me.

**Comment by yashkansal** [comment]
I would like to implement this in javascript. Plz, assign me.

**Comment by kashika3101** [comment]
I will like to implement the quick sort algorithm in c++. Please assign this issue as a part of Hackthoberfest 2020.
