### ISSUE TITLE
Add hacktoberfest label to the repoaitory

### ISSUE THREAD

**Issue by Kanhakhatri065** [ephremdeme/data-structure-and-algorithms#317]
@ephremdeme please add the Hacktoberfest label to the repository to make it eligible to participate in Hacktoberfest2020. As, most of our contributors are Hacktoberfest aspirants we don't want their effort to go in vain.

**Comment by ephremdeme** [comment]
@Kanhakhatri065  Anyone who creates an issues can label the issue. Simply go to any issues, example this, then click 'Label' and finally select 'hacktoberfest'. Its over as simple as that.

**Comment by Kanhakhatri065** [comment]
Noted.
