### ISSUE TITLE
Algorithm for checking if a string can be rearranged into a palindrome

### ISSUE THREAD

**Issue by colossal-pepe** [ephremdeme/data-structure-and-algorithms#321]
I would like to do this in C++. Also for hacktoberfest. Another question, if I ended up doing this, where should I put the file?

**Comment by Kanhakhatri065** [comment]
Sure, go ahead. You can put it in Algorithms folder

**Comment by christopherwalkerml** [comment]
PR: https://github.com/ephremdeme/data-structure-and-algorithms/pull/338

**Comment by krishnmohan19** [comment]
hey @Kanhakhatri065 .
plz assign me this in any of java/c#.

**Comment by Druffl3** [comment]
@Kanhakhatri065 , implemented the solution in C# and submitted a PR #351
