### ISSUE TITLE
Check Prime Number

### ISSUE THREAD

**Issue by ephremdeme** [ephremdeme/data-structure-and-algorithms#37]
Build a program that checks weather a given number is a prime or not. Don't forget to optimize for performance.
Implement it using any language.

input: 1109
output: True

input: 1110
output: False

**Comment by sparshs413** [comment]
Please assign me this task!!

**Comment by ephremdeme** [comment]
Comment your preferred language below.

**Comment by sparshs413** [comment]
I would do it in C++

**Comment by ephremdeme** [comment]
Great, Go on do it. I just completed it using JavaScript.

**Comment by malathit** [comment]
Shall I implement the program in python?

**Comment by femakin** [comment]
Please can I implement with R

**Comment by ephremdeme** [comment]
Yeah sure. please do.

**Comment by roninJosue** [comment]
Hello, can I implement it in JavaScript?

**Comment by skamp91** [comment]
Hey :)
I would like to implement this task in C#.

GoodRegards

**Comment by ephremdeme** [comment]
Yes you can implement in what ever language you want, so just Pull Request.
