### ISSUE TITLE
Linear search

### ISSUE THREAD

**Issue by ephremdeme** [ephremdeme/data-structure-and-algorithms#4]
Linear search implementation with any language

> Input: array and search key

> Output: print index of key or return -1 if not found

**Comment by Jaideep07** [comment]
I would like to do this 😃

**Comment by sparshs413** [comment]
I have created a pull request please, review.

**Comment by dolonmandal** [comment]
Please Assign :)

**Comment by sparshs413** [comment]
Will take care next time @dolonmandal

**Comment by ephremdeme** [comment]
i have reviewed every PR and merged them.

Now, implement in any other language not the one being implemented

**Comment by ephremdeme** [comment]
@all-contributors please add sparshs413 for code

**Comment by mananchawla2005** [comment]
Any languages left for Linear Search to be implemented? @ephremdeme

**Comment by gitaalekhyapaul** [comment]
I would like to contribute in Linear Search using Javascript. Please assign @ephremdeme

**Comment by mananchawla2005** [comment]
Assign me for python @ephremdeme

**Comment by vyasriday** [comment]
I will add in JavaScript

**Comment by vyasriday** [comment]
@ephremdeme Added linear search in golang https://github.com/ephremdeme/data-structure-and-algorithms/pull/71

**Comment by Kanhakhatri065** [comment]
We have more than enough contributions for this issue. So,I'm gonna close this issue.
