### ISSUE TITLE
Implement Shell Sort 

### ISSUE THREAD

**Issue by yashasvimisra2798** [ephremdeme/data-structure-and-algorithms#45]
Write a program to implement the shell sort algorithm.

**Comment by yashasvimisra2798** [comment]
I can do this task in C++. Please assign this to me, I want to work on this as a part of Hacktoberfest!

**Comment by ephremdeme** [comment]
Okay here you go.

**Comment by yashasvimisra2798** [comment]
Thanks @ephremdeme

**Comment by Kanhakhatri065** [comment]
I can do this in python. Assign this to me.
