### ISSUE TITLE
Implementation of firstDuplicate

### ISSUE THREAD

**Issue by tlynx538** [ephremdeme/data-structure-and-algorithms#94]
_--Adapted from CodeSignal.com---_
Given an array **a** that contains only numbers in the range from **1** to **a.length**, find the first duplicate number for which the second occurrence has the minimal index. In other words, if there are more than **1** duplicated numbers, return the number for which the second occurrence has **a** smaller index than the second occurrence of the other number does. If there are no such elements, return **-1**.

Example

For a = [2, 1, 3, 5, 3, 2], the output should be firstDuplicate(a) = 3.

There are 2 duplicates: numbers 2 and 3. The second occurrence of 3 has a smaller index than the second occurrence of 2 does, so the answer is 3.

For a = [2, 2], the output should be firstDuplicate(a) = 2;

For a = [2, 4, 3, 5, 1], the output should be firstDuplicate(a) = -1.
Input/Output

[execution time limit] 4 seconds (py3)

[input] array.integer a

Guaranteed constraints:
1 ≤ a.length ≤ 105,
1 ≤ a[i] ≤ a.length.

[output] integer

The element in a that occurs in the array more than once and has the minimal index for its second occurrence. If there are no such elements, return -1.

**Comment by shaswatsingh19** [comment]
I would like to work on it in python

**Comment by tlynx538** [comment]
> I would like to work on it in python

For sure no problem

**Comment by MaticBabnik** [comment]
I can do C# and js

**Comment by tlynx538** [comment]
> I can do C# and js

Great, can you contribute either of any preferred language?

**Comment by MaticBabnik** [comment]
> > I can do C# and js
> 
> Great, can you contribute either of any preferred language?

Did both, just tell me in which folder do I put them and I'll send a PR.

**Comment by tlynx538** [comment]
> > > I can do C# and js
> > 
> > 
> > Great, can you contribute either of any preferred language?
> 
> Did both, just tell me in which folder do I put them and I'll send a PR.

in the Algorithms folder

**Comment by ankitaugale23** [comment]
I would like to work on it in c++

**Comment by reethu-annjo** [comment]
I would like to work on it in java

**Comment by MaticBabnik** [comment]
#201 pull?

**Comment by tlynx538** [comment]
@ankitaugale23 @reethu-annjo @shaswatsingh19 please create a pull request in submitting your implementation and make sure you put it into /problems folder

**Comment by ankitaugale23** [comment]
> @ankitaugale23 @reethu-annjo @shaswatsingh19 please create a pull request in submitting your implementation and make sure you put it into /problems folder

I have made a PR #316 . Kindly check

**Comment by tlynx538** [comment]
> > @ankitaugale23 @reethu-annjo @shaswatsingh19 please create a pull request in submitting your implementation and make sure you put it into /problems folder
> 
> I have made a PR #316 . Kindly check

You're good to go.
